### PR TITLE
Added TLD, SLD, FQDN dashboard

### PR DESCRIPTION
**Pull request by harper-carroll**
Screen shot as of June 12, 9:54 AM: 

screen shot 2016-07-12 at 9 53 26 am

### CODE REVIEW

**Comment by KjellKod** [comment]
@harper-carroll let's ask Rob and Matt to look at this once you have tested the range that you were working on

**Comment by KjellKod** [comment]
screen shot 2016-07-12 at 10 54 44 am


something is broken

**Comment by KjellKod** [comment]
@harper-carroll I might have missed something? but I built and installed kibana again after merging your protobuffer PR. It still shows the same error.

**Comment by KjellKod** [comment]
To clarify. I rebuilt from kibana and up I didn't rebuilt from NMProtobuffers since I didn't think that was needed. I'll do it from NMProtobuffers too just in case I've misunderstood how the PB is installed and used.

**Comment by harper-carroll** [comment]
Update: you need to delete today’s index because the .raw mappings are only registered when a new index is created (i.e. you would have to wait until tomorrow to see the data).

**Comment by KjellKod** [comment]
sweet that did it.
screen shot 2016-07-12 at 11 35 38 am

**Comment by KjellKod** [comment]
👍  @john-gress, @shwetabhandare, @craig-cogdill, @alexweltman please take a look at this PR + the system rule one 

You can see it running on 10.3.3.55 (!2)

**Comment by KjellKod** [comment]
👍  with the SLD raw changes.

**Comment by KjellKod** [comment]
I'll go ahead and merge this now. If someone want's to re-review it then ask @harper-carroll or me and we can point you to an IP where it can be seen.

**Comment by KjellKod** [comment]
The SLD worked fine. I had to delete the .kibana index before I saw the .raw changes but then it worked fine. 

screen shot 2016-07-12 at 11 10 21 pm

**Pull request merged**
