### PR TITLE
First Pass at 'Daymode' Styling

### PR DESCRIPTION
**Pull request by alexweltman**
- a few easy changes. Button colors, link colors, graph colors
- UX has recommended we do more, but I'm pushing those recommendations to the next release

### CODE REVIEW

**Comment by craig-cogdill** [comment]
👍  How hard will this make it to update Kibana if we ever want to?

**Comment by alexweltman** [comment]
the kibana update will overwrite these changes... right now we have a format for modularizing our JS code so it doesn't get overwritten, but now our css styles.

**Comment by john-gress** [comment]
👍

**Comment by yannick-polius** [comment]
:+1:

**Comment by craig-cogdill** [comment]
👍  from Craig and Kjell

**Pull request merged**
